blank_issues_enabled: true
contact_links:
  - name: Slack Community
    url: https://join.slack.com/t/meetless/shared_invite/zt-3qofaf1di-2hRqBAtnyrTWAos0MQ5dzQ
    about: Join the Meetless community on Slack â€” ask questions, share wins, see the product live
